apiVersion: v1
kind: Service
metadata:
  name: whoami-service-canary
spec:
  selector:
    app: whoami  # This will select pods from both deployments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
