apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment-v1
  labels:
    app: whoami
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
      version: v1
  template:
    metadata:
      labels:
        app: whoami
        version: v1
    spec:
      containers:
      - name: whoami
        image: congtaojiang/whoami-nodejs-express:latest
        ports:
        - containerPort: 8000
